// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vuart.cpp"
#include "Vuart___024root__DepSet_hd9b01d36__0.cpp"
#include "Vuart___024root__DepSet_ha21bd04d__0.cpp"
#include "Vuart___024root__Slow.cpp"
#include "Vuart___024root__DepSet_ha21bd04d__0__Slow.cpp"
#include "Vuart__Syms.cpp"
